apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
 namespace: istio-system
 name: wildcard-certificate-tls
spec:
 acme:
   server: https://acme-v02.api.letsencrypt.org/directory
   email: tsama2297@gmail.com
   privateKeySecretRef:
     name: wildcard-certificate-tls
   solvers:
   - http01:
       ingress:
         class: nginx